// Generated by Wrangler on Tue Apr 30 2024 02:46:41 GMT+0900 (Korean Standard Time)
// by running `wrangler types ./src/workers-env.d.ts`

interface Env {
  HASHNODE_TOKEN: string;
  HASHNODE_PUBLICATION_ID: string;
}
